apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: bda-backend
spec:
  selector:
    matchLabels:
      app: bda-backend
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bda-backend
    spec:
      containers:
      - name: bda-backend
        image: siddharths2710/bda_backend:latest
        resources:
          limits:
            memory: "900Mi"
            cpu: "300m"
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "$MONGO_URI"
        - name: FLASK_PORT
          value: "$FLASK_PORT"
      restartPolicy: Always
